# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/shanty.hritesh_gmail.com#ext#@shantyhriteshgmail.onmicrosoft.com/New Pipeline 2025-10-27 14:28")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM spotify_cata.gold.sample_trips_oct_27_1428"))

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from spotify_cata.gold.dimtrack
# MAGIC where '_END_AT' is not null

# COMMAND ----------


